# test

GET http://localhost:5000/todos
###
GET http://localhost:5000/todos/3
###

POST http://localhost:5000/todos
Content-Type: application/json

{
  "description": "go for test"
}

###
POST http://localhost:5000/todos
Content-Type: application/json

{
  "description": "I need to clean my room"
}

###
PUT http://localhost:5000/todos/2
Content-Type: application/json

{
  "description" : "patch reqsxxsst test"
}

###
DELETE http://localhost:5000/todos/1